########## Volcano plot v1 ##########

#This needs to come out of the results object. I convert the results object to a dataframe to easily remove NA's
#Generated by Cooks distance cutoffs
#I do not restrict to FDR < 0.05 so I can get an actual volcano. 

MB2_padj <-  na.omit(MB2)
View(MB2_padj)
cols <- densCols(MB2_padj$log2FoldChange, -log10(MB2_padj$pvalue))
plot(MB2_padj$log2FoldChange, -log10(MB2_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(MB2_padj$log2FoldChange) > 1 & MB2_padj$padj < alpha 
text(MB2_padj$log2FoldChange[gn.selected],
     -log10(MB2_padj$padj)[gn.selected],
     lab=MB2_padj$row[gn.selected ], cex=0.4)


MB6_padj <-  na.omit(MB6)
View(MB6_padj)
cols <- densCols(MB6_padj$log2FoldChange, -log10(MB6_padj$pvalue))
plot(MB6_padj$log2FoldChange, -log10(MB6_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(MB6_padj$log2FoldChange) > 1 & MB6_padj$padj < alpha 
text(MB6_padj$log2FoldChange[gn.selected],
     -log10(MB6_padj$padj)[gn.selected],
     lab=MB6_padj$row[gn.selected ], cex=0.4)


MB24_padj <-  na.omit(MB24)
View(MB24_padj)
cols <- densCols(MB24_padj$log2FoldChange, -log10(MB24_padj$pvalue))
plot(MB24_padj$log2FoldChange, -log10(MB24_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(MB24_padj$log2FoldChange) > 1 & MB24_padj$padj < alpha 
text(MB24_padj$log2FoldChange[gn.selected],
     -log10(MB24_padj$padj)[gn.selected],
     lab=MB24_padj$row[gn.selected ], cex=0.4)


MB48_padj <-  na.omit(MB48)
View(MB48_padj)
cols <- densCols(MB48_padj$log2FoldChange, -log10(MB48_padj$pvalue))
plot(MB48_padj$log2FoldChange, -log10(MB48_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(MB48_padj$log2FoldChange) > 1 & MB48_padj$padj < alpha 
text(MB48_padj$log2FoldChange[gn.selected],
     -log10(MB48_padj$padj)[gn.selected],
     lab=MB48_padj$row[gn.selected ], cex=0.4)

	 
TB2 <- results(dds, contrast=c("TT","TB2","CN2"), tidy = TRUE)
TB2_padj <-  na.omit(TB2)
View(TB2_padj)
cols <- densCols(TB2_padj$log2FoldChange, -log10(TB2_padj$pvalue))
plot(TB2_padj$log2FoldChange, -log10(TB2_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(TB2_padj$log2FoldChange) > 2.5 & TB2_padj$padj < alpha 
text(TB2_padj$log2FoldChange[gn.selected],
     -log10(TB2_padj$padj)[gn.selected],
     lab=rownames(TB2_padj)[gn.selected ], cex=0.4)
	 
TB6 <- results(dds, contrast=c("TT","TB6","CN6"), tidy = TRUE)
TB6_padj <-  na.omit(TB6)
View(TB6_padj)
cols <- densCols(TB6_padj$log2FoldChange, -log10(TB6_padj$pvalue))
plot(TB6_padj$log2FoldChange, -log10(TB6_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(TB6_padj$log2FoldChange) > 2.5 & TB6_padj$padj < alpha 
text(TB6_padj$log2FoldChange[gn.selected],
     -log10(TB6_padj$padj)[gn.selected],
     lab=rownames(TB6_padj)[gn.selected ], cex=0.4)
	 
TB24 <- results(dds, contrast=c("TT","TB24","CN2"), tidy = TRUE)
TB24_padj <-  na.omit(TB24)
View(TB24_padj)
cols <- densCols(TB24_padj$log2FoldChange, -log10(TB24_padj$pvalue))
plot(TB24_padj$log2FoldChange, -log10(TB24_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(TB24_padj$log2FoldChange) > 2.5 & TB24_padj$padj < alpha 
text(TB24_padj$log2FoldChange[gn.selected],
     -log10(TB24_padj$padj)[gn.selected],
     lab=rownames(TB24_padj)[gn.selected ], cex=0.4)

	 
TB48 <- results(dds, contrast=c("TT","TB48","CN2"), tidy = TRUE)
TB48_padj <-  na.omit(TB48)
View(TB48_padj)
cols <- densCols(TB48_padj$log2FoldChange, -log10(TB48_padj$pvalue))
plot(TB48_padj$log2FoldChange, -log10(TB48_padj$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
abline(v=0)
abline(v=c(-1,1), col="brown")
abline(h=-log10(alpha), col="brown")
gn.selected <- abs(TB48_padj$log2FoldChange) > 2.5 & TB48_padj$padj < alpha 
text(TB48_padj$log2FoldChange[gn.selected],
     -log10(TB48_padj$padj)[gn.selected],
     lab=rownames(TB48_padj)[gn.selected ], cex=0.4)


########## Volcano plot v2 ##########
#Volcano plots from the package enhancedvolcano. I prefer the user control of these. 

if (!requireNamespace("BiocManager", quietly = TRUE)) 
install.packages("BiocManager")
BiocManager::install("EnhancedVolcano")

library(EnhancedVolcano)
library(readr)
setwd("E:/Users/Tom/Dropbox/New Alv_mac analysis/Analysis/DE analysis/Data/upsetr")
MB_2hpi_DE_genes_v <- read_csv("MB_2hpi_DE_genes_v.csv")
MB2_padj <- na.omit(MB_2hpi_DE_genes_v)
MB2_padj_LFC <- subset(MB2_padj, abs(log2FoldChange) > 1)
MB2_padj_LFC <- MB2_padj_LFC[order(MB2_padj_LFC$padj),]
MB2_padj_topten <- MB2_padj_LFC[c(1:10),]
EnhancedVolcano(data.frame(MB2_padj), lab = MB2_padj$X1,  x = "log2FoldChange", y = "padj", pCutoff = 5e-2,
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 2hpi versus Infected 2hpi",xlim = c(-6, 6), ylim = c(0, -log10(10e-7)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")


MB6_padj <- na.omit(MB6)
MB6_padj_LFC <- subset(MB6_padj, abs(log2FoldChange) > 1)
MB6_padj_LFC <- MB6_padj_LFC[order(MB6_padj_LFC$padj),]
MB6_padj_topten <- MB6_padj_LFC[c(1:15),]
EnhancedVolcano(MB6_padj, lab = rownames(MB6_padj), selectLab = rownames(MB6_padj_topten), x = "log2FoldChange", y = "padj", pCutoff = 5e-2, 
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 6hpi versus Infected 6hpi",xlim = c(-6, 6), ylim = c(0, -log10(10e-6)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")

MB24_padj <- na.omit(MB24)
MB24_padj_LFC <- subset(MB24_padj, abs(log2FoldChange) > 1)
MB24_padj_LFC <- MB24_padj_LFC[order(MB24_padj_LFC$padj),]
MB24_padj_topten <- MB24_padj_LFC[c(1:15),]
EnhancedVolcano(MB24_padj, lab = rownames(MB24_padj), selectLab = rownames(MB24_padj_topten), x = "log2FoldChange", y = "padj", pCutoff = 5e-2, 
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 24hpi versus Infected 24hpi",xlim = c(-8, 8), ylim = c(0, -log10(10e-22)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")
				
MB48_padj <- na.omit(MB48)
MB48_padj_LFC <- subset(MB48_padj, abs(log2FoldChange) > 1)
MB48_padj_LFC <- MB48_padj_LFC[order(MB48_padj_LFC$padj),]
MB48_padj_topten <- MB48_padj_LFC[c(1:15),]
EnhancedVolcano(MB48_padj, lab = MB48_padj$ENTREZID, selectLab = rownames(MB48_padj_topten), x = "log2FoldChange", y = "padj", pCutoff = 5e-2, 
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 48hpi versus Infected 48hpi",xlim = c(-9, 9), ylim = c(0, -log10(10e-43)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")

TB2_padj <- na.omit(MB2)
TB2_padj_LFC <- subset(TB2_padj, abs(log2FoldChange) > 1)
TB2_padj_LFC <- TB2_padj_LFC[order(TB2_padj_LFC$padj),]
TB2_padj_topten <- TB2_padj_LFC[c(1:10),]
EnhancedVolcano(TB2_padj, lab = rownames(TB2_padj), x = "log2FoldChange", y = "padj", pCutoff = 5e-2, 
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 2hpi versus Infected 2hpi",xlim = c(-6, 6), ylim = c(0, -log10(10e-6)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")

TB6_padj <- na.omit(TB6)
TB6_padj_LFC <- subset(TB6_padj, abs(log2FoldChange) > 1)
TB6_padj_LFC <- TB6_padj_LFC[order(TB6_padj_LFC$padj),]
TB6_padj_topten <- TB6_padj_LFC[c(1:10),]
EnhancedVolcano(TB6_padj, lab = rownames(TB6_padj), selectLab = rownames(TB6_padj_topten), x = "log2FoldChange", y = "padj", pCutoff = 5e-2, 
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 6hpi versus Infected 6hpi",xlim = c(-6, 6), ylim = c(0, -log10(10e-6)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")

TB24_padj <- na.omit(TB24)
TB24_padj_LFC <- subset(TB24_padj, abs(log2FoldChange) > 1)
TB24_padj_LFC <- TB24_padj_LFC[order(TB24_padj_LFC$padj),]
TB24_padj_topten <- TB24_padj_LFC[c(1:10),]
EnhancedVolcano(TB24_padj, lab = rownames(TB24_padj), selectLab = rownames(TB24_padj_topten), x = "log2FoldChange", y = "padj", pCutoff = 5e-2, 
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 24hpi versus Infected 24hpi",xlim = c(-7, 7), ylim = c(0, -log10(10e-10)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")
				
TB48_padj <- na.omit(TB48)
TB48_padj_LFC <- subset(TB48_padj, abs(log2FoldChange) > 1)
TB48_padj_LFC <- TB48_padj_LFC[order(MB48_padj_LFC$padj),]
TB48_padj_topten <- TB48_padj_LFC[c(1:10),]
EnhancedVolcano(TB48_padj, lab = rownames(TB48_padj), selectLab = rownames(TB48_padj_topten), x = "log2FoldChange", y = "padj", pCutoff = 5e-2, 
                col=c("#666666", "#666666", "#4d94ff", "#ff3333"), colAlpha = 0.8, FCcutoff = 1, transcriptPointSize = 2, 
                transcriptLabSize = 3, title = "Control 48hpi versus Infected 48hpi",xlim = c(-8, 8), ylim = c(0, -log10(10e-22)), 
                legend=c("NS", "", "FDR", "Log2FC & FDR "), border = "full", gridlines.major = FALSE, gridlines.minor = FALSE, borderColour = "#4d4d4d")
